[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shipjson = { path = "../shipjson" }
local-ip-address = "0.5.7"
serde_json = "1.0.113"
serde = "1.0.196"